services:
  solutions.todolist.webapi:
    image: ghcr.io/alifaisal101/solutions.todolist.webapi:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
